version : 0.2
phase :
  install:
    runtime-versions:
      nodejs: 12
    commands :
      - npm install -g @angular/cli@9.0.6
  pre_build :
    commands :
      - npm install
  build :
    commands :
      - ng build --prod
    finally :
      - echo Hi Abhishek !!
artifacts:
  base-directory: dist/my-angular-app
  files:
    - '**/*'
