version : 0.2
phase :
  install:
    runtime-versions:
      nodejs: 12
    commands :
      - npm install -g @angular/cli@9.0.6
  pre_build :
    commands :
      - npm install
      - npm install sweetalert2
      - npm install bootstrap@3.3.7
  build :
    commands :
      - ng build --prod
    finally :
      - echo Hi Abhishek !!
artifacts:
  files:
    - '**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'
